# Generated by Django 5.1 on 2024-08-28 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karatestyles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='movimentos/')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posture_style', to='karatestyles.karatestyle')),
            ],
        ),
    ]
