# Generated by Django 5.1 on 2024-09-16 12:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojos', '0002_alter_dojo_sensei'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Não é permitida avaliação inferior a ZERO!'), django.core.validators.MaxValueValidator(5, 'Não é permitida avaliação superior a CINCO!')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dojos', to='dojos.dojo')),
            ],
        ),
    ]
