# Generated by Django 5.1 on 2024-10-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graduations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karateca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celphone', models.CharField(blank=True, max_length=60, null=True)),
                ('graduation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='graduation', to='graduations.graduation')),
            ],
        ),
    ]
