# Generated by Django 5.1 on 2024-08-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karateca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(blank=True, choices=[('MAS', 'Masculino'), ('FEM', 'Feminino')], max_length=60, null=True)),
                ('street', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('zipcode', models.CharField(blank=True, max_length=16, null=True)),
                ('complement', models.CharField(blank=True, max_length=60, null=True)),
                ('district', models.CharField(blank=True, max_length=160, null=True)),
                ('city', models.CharField(blank=True, max_length=160, null=True)),
                ('state', models.CharField(blank=True, max_length=160, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
