# Generated by Django 5.1 on 2024-08-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatecas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karateca',
            name='graduation',
            field=models.CharField(blank=True, choices=[('7kyu', 'Faixa Branca'), ('6kyu', 'Faixa Amarela'), ('5kyu', 'Faixa Vermelha'), ('4kyu', 'Faixa Laranja'), ('3kyu', 'Faixa Verde'), ('2kyu', 'Faixa Roxa'), ('1kyu', 'Faixa Marrom')], max_length=60, null=True),
        ),
    ]
