# Generated by Django 5.1 on 2024-10-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatecas', '0002_karateca_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karateca',
            name='graduation',
            field=models.CharField(blank=True, choices=[('7kyu', 'Faixa Branca'), ('6kyu', 'Faixa Amarela'), ('5kyu', 'Faixa Vermelha'), ('4kyu', 'Faixa Laranja'), ('3kyu', 'Faixa Verde'), ('2kyu', 'Faixa Roxa'), ('1kyu', 'Faixa Marrom'), ('1dan', 'Faixa Preta'), ('2dan', 'Faixa Preta'), ('3dan', 'Faixa Preta'), ('4dan', 'Faixa Preta'), ('5dan', 'Faixa Preta'), ('6dan', 'Faixa Preta'), ('7dan', 'Faixa Preta'), ('8dan', 'Faixa Preta'), ('9dan', 'Faixa Preta'), ('10dan', 'Faixa Preta')], max_length=60, null=True),
        ),
    ]
