# Generated by Django 5.1 on 2024-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatecas', '0003_alter_karateca_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karateca',
            name='graduation',
            field=models.CharField(blank=True, choices=[('7kyu', 'Faixa Branca'), ('6kyu', 'Faixa Amarela'), ('5kyu', 'Faixa Vermelha'), ('4kyu', 'Faixa Laranja'), ('3kyu', 'Faixa Verde'), ('2kyu', 'Faixa Roxa'), ('1kyu', 'Faixa Marrom'), ('1dan', '1º Dan Faixa Preta'), ('2dan', '2º Dan Preta'), ('3dan', '3º Dan Preta'), ('4dan', '4º Dan Preta'), ('5dan', '5º Dan Preta'), ('6dan', '6º Dan Preta'), ('7dan', '7º Dan Preta'), ('8dan', '8º Dan Preta'), ('9dan', '9º Dan Preta'), ('10dan', '10º Dan Preta')], max_length=60, null=True),
        ),
    ]
