# Generated by Django 5.1 on 2024-10-02 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_alter_dojo_sensei'),
        ('karatecas', '0004_alter_karateca_graduation'),
    ]

    operations = [
        migrations.AddField(
            model_name='karateca',
            name='dojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='karatekadojo', to='dojos.dojo'),
        ),
    ]
