# Generated by Django 5.1 on 2024-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatecas', '0005_karateca_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='karateca',
            name='celphone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='karateca',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='karateca',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
