# Generated by Django 5.1 on 2024-08-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15)),
                ('graduation', models.CharField(blank=True, choices=[('1Dan', '1º Dan - Faixa preta'), ('2Dan', '2º Dan - Faixa preta'), ('3Dan', '3º Dan - Faixa preta'), ('4Dan', '4º Dan - Faixa preta'), ('5Dan', '5º Dan - Faixa preta'), ('6Dan', '6º Dan - Faixa preta'), ('7Dan', '7º Dan - Faixa preta'), ('8Dan', '8º Dan - Faixa preta'), ('9Dan', '9º Dan - Faixa preta'), ('10Dan', '10º Dan - Faixa preta')], max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('celPhone', models.CharField(max_length=60)),
            ],
        ),
    ]
