# Generated by Django 5.1 on 2024-08-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseis', '0002_alter_sensei_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensei',
            name='graduation',
            field=models.CharField(blank=True, choices=[('1Dan', '1º Dan - Faixa preta'), ('2Dan', '2º Dan - Faixa preta'), ('3Dan', '3º Dan - Faixa preta'), ('4Dan', '4º Dan - Faixa preta'), ('5Dan', '5º Dan - Faixa preta'), ('6Dan', '6º Dan - Faixa preta'), ('7Dan', '7º Dan - Faixa preta'), ('8Dan', '8º Dan - Faixa preta'), ('9Dan', '9º Dan - Faixa preta'), ('10Dan', '10º Dan - Faixa preta')], max_length=60, null=True),
        ),
    ]
