# Generated by Django 5.1 on 2024-08-28 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('senseis', '0003_alter_sensei_graduation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('site', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=160, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.IntegerField()),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('sensei', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senseis', to='senseis.sensei')),
            ],
        ),
    ]
