# Generated by Django 5.1 on 2024-10-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=200)),
                ('tradename', models.CharField(blank=True, max_length=200, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.IntegerField()),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=160, null=True)),
                ('city', models.CharField(blank=True, max_length=160, null=True)),
                ('state', models.CharField(blank=True, max_length=160, null=True)),
                ('country', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
    ]
