# Generated by Django 5.1 on 2024-08-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0001_initial'),
        ('senseis', '0003_alter_sensei_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='sensei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='senseis', to='senseis.sensei'),
        ),
    ]
