# Generated by Django 5.1 on 2024-10-03 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('dojos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='aulas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auladojo', to='classes.aula'),
        ),
    ]
