# Generated by Django 5.1 on 2024-10-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_dojo_aulas'),
        ('senseis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='sensei',
            field=models.ManyToManyField(related_name='sensei', to='senseis.sensei'),
        ),
    ]
