# Generated by Django 5.1 on 2024-10-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('dojos', '0003_dojo_sensei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='aulas',
        ),
        migrations.AddField(
            model_name='dojo',
            name='aulas',
            field=models.ManyToManyField(related_name='auladojo', to='classes.aula'),
        ),
    ]
