# Generated by Django 5.1 on 2024-10-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='idTurno',
        ),
    ]
