# Generated by Django 5.1 on 2024-08-28 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karatestyles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('movie_workout', models.FileField(blank=True, null=True, upload_to='workout/')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout_style', to='karatestyles.karatestyle')),
            ],
        ),
    ]
