# Generated by Django 5.1 on 2024-08-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KarateStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100)),
                ('gran_master', models.CharField(blank=True, max_length=100, null=True)),
                ('province_origin', models.CharField(blank=True, max_length=160, null=True)),
                ('year_create', models.IntegerField()),
            ],
        ),
    ]
