# Generated by Django 5.1 on 2024-09-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karatestyles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karatestyle',
            name='gran_master',
        ),
        migrations.RemoveField(
            model_name='karatestyle',
            name='province_origin',
        ),
        migrations.RemoveField(
            model_name='karatestyle',
            name='year_create',
        ),
    ]
