# Generated by Django 5.1 on 2024-08-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=60)),
                ('time', models.CharField(choices=[('1º', '10:00 - 11:15'), ('2º', '18:00 - 19:15'), ('3º', '19:30 - 20:45'), ('4º', '10:00 - 12:00')], max_length=40)),
            ],
        ),
    ]
