# Generated by Django 5.1 on 2024-08-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timne',
            new_name='Time',
        ),
    ]
