# Generated by Django 5.1 on 2024-09-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_alter_dojo_sensei'),
        ('times', '0002_rename_timne_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='dojo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dojo_time', to='dojos.dojo'),
        ),
    ]
