# Generated by Django 5.1 on 2024-09-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_time_dojo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='dojo',
        ),
    ]
