# Generated by Django 5.1 on 2024-08-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100)),
                ('name_kata', models.CharField(max_length=100)),
                ('qtde_moviments', models.IntegerField()),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('duracao', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
