# Generated by Django 5.1 on 2024-08-27 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kata',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
