# Generated by Django 5.1 on 2024-08-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katas', '0002_kata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kata',
            name='style',
            field=models.CharField(choices=[('Goju', 'Goju-Ryu'), ('Shoto', 'Shotokan'), ('Wado', 'Wado-Ryu'), ('Shito', 'Shito-Ryu'), ('Shorin', 'Shorin-Ryu')], max_length=100),
        ),
    ]
