# Generated by Django 5.1 on 2024-08-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katas', '0003_alter_kata_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
