# Generated by Django 5.1 on 2024-08-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katas', '0004_alter_kata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kata',
            name='duracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kata',
            name='style',
            field=models.CharField(blank=True, choices=[('Goju', 'Goju-Ryu'), ('Shoto', 'Shotokan'), ('Wado', 'Wado-Ryu'), ('Shito', 'Shito-Ryu'), ('Shorin', 'Shorin-Ryu')], max_length=160, null=True),
        ),
    ]
