# Generated by Django 5.1 on 2024-08-28 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatestyles', '0001_initial'),
        ('katas', '0005_alter_kata_duracao_alter_kata_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kata',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='styles', to='karatestyles.karatestyle'),
        ),
    ]
