# Generated by Django 5.1 on 2024-09-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katas', '0006_alter_kata_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kata',
            old_name='name_kata',
            new_name='nameKata',
        ),
    ]
