# Generated by Django 5.1 on 2024-10-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katas', '0007_rename_name_kata_kata_namekata'),
    ]

    operations = [
        migrations.AddField(
            model_name='kata',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
